version: '3.4'
networks:
  e0:
    external: true
  i0:
    external: true

services:

    # The Application
    api:
        image: template-api:latest
        ports:
            - 8082:8080
        depends_on:
            - redis
            - mongo
        networks:
            - i0
        environment:
            - MONGOLAB_URL=mongodb://mongo/giro
            - LOG_MONGOLAB_URL=mongodb://mongo/giroLogs
            - REDIS_URL=redis://redis:6379/1

    # The Web Server
    clock:
        image: template-clock:latest
        depends_on:
            - redis
            - mongo
        networks:
            - i0
        environment:
            - MONGOLAB_URL=mongodb://mongo/giro
            - LOG_MONGOLAB_URL=mongodb://mongo/giroLogs
            - REDIS_URL=redis://redis:6379/1

    # The Worker
    worker:
        image: template-worker:latest
        depends_on:
            - redis
            - mongo
        networks:
            - i0
        environment:
            - MONGOLAB_URL=mongodb://mongo/giro
            - LOG_MONGOLAB_URL=mongodb://mongo/giroLogs
            - REDIS_URL=redis://redis:6379/1

    # MongoDB Admin
    mongoadmin:
        image: mongo-express
        depends_on:
            - mongo
        networks:
            - e0
            - i0
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
        ports:
            - "8083:8081"

    # Redis
    redis:
        image: redis
        networks:
            - i0

    # Mongo
    mongo:
        image: mongo:5.0.6
        networks:
            - i0